
Production
NODE_ENV=production

WHATSAPP_AUTH_PATH=./wwebjs_auth

SUPABASE_URL=https://YOUR_PROJECT.supabase.co
SUPABASE_SERVICE_ROLE_KEY=YOUR_SERVICE_ROLE_KEY
SUPABASE_WHATSAPP_BUCKET=whatsapp-sessions

WHATSAPP_BACKUP_INTERVAL_MS=60000

BROADCAST_INTERVAL_MS=30000